### ISSUE TITLE
qualitative color maps

### ISSUE THREAD

**Issue by gvoysey** [geojames/CloudCompareColor#1]
hi -- thanks for this work!

i have been scratching my head a bit over how to accomplish what i want, and perhaps you know, if you've been able to make all these color maps!  In particular, i'm interested in how to make [qualitative](https://matplotlib.org/stable/users/explain/colors/colormaps.html#qualitative) color maps -- one where colors for a particular value have a semantic meaning but don't lie on a gradient relative to their neighboring colors in the map.

I'd like to have a color map that map the classification scalar field of a las file to a particular color -- so i have integer values that lie between [0, 255] (lasfile 1.4, point format 6) and i want all the class 2 points to be brown, all class 3 to be yellow, ... etc. 

this is what i've attempted so far, but when i use the following colormap in cloudcompare, all i get is a solid dark red coloring: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<CloudCompare>
    <ColorScale version="1">
        <Properties>
            <name>classification-gv</name>
            <uuid>{67147e26-8743-4881-bae9-54c996012fda}</uuid>
            <absolute>1</absolute>
            <minValue>2</minValue>
            <range>155</range>
        </Properties>
        <Data>
          <!--  rgb(99,69, 44) brown -->
          <step r="99" g="69" b="44" pos="0"/> <!--2/ground-->

          <!-- rgb(249,240,107) yellow-->
          <step r="249" g="240" b="107" pos="0.00653594771242"/> <!--3/low veg-->

          <!-- rgb(38,162,105) dark green-->
          <step r="38" g="162" b="105" pos="0.0130718954248"/>   <!--4/medium veg-->

          <!--  rgb(17,247,14) light green-->
          <step r="17" g="247" b="14" pos="0.0196078431373"/>    <!--5/high veg-->

          <!--  rgb(0,0,0) black -->
          <step r="0" g="0" b="0" pos="0.0522875816993"/>        <!--10/to be deleted-->

          <!--  rgb(119,118,123) grey-->
          <step r="119" g="118" b="123" pos="0.0915032679739"/>  <!--16/manmade structure-->

          <!--  -->
          <!-- 17 / previously 3/low veg now 16/structure -->

          <!--  -->
          <!-- 18 / previously 4/medium veg now 16/structure -->

          <!-- rgb(246,245,244) cream-->
          <step r="246" g="245" b="244" pos="0.967320261438"/>   <!--150/poles-->

          <!--  rgb(26,95,180) blue-->
          <step r="26" g="95" b="180" pos="0.97385620915"/>      <!--151/primary wire-->

          <!--  rgb(255,0,0) red -->
          <step r="255" g="0" b="0" pos="0.97385620915"/>        <!--152/previously 16/structure, now wire-->

          <!--  rgb(120,18,188) purple-->
          <step r="120" g="18" b="188" pos="0.980392156863"/>    <!--153/previously 150/pole, now wire-->

          <!--  rgb(224,28,206) magenta-->
          <step r="224" g="28" b="206" pos="0.986928104575"/>    <!--154/previously 150/pole, now service trap-->

          <!--  rgb(168,139,73) olive-->
          <step r="168" g="139" b="73" pos="0.993464052288"/>    <!--155/unstrung wire-->

          <!--  rgb(229,165,10) orange -->
          <step r="229" g="165" b="10" pos="1"/>
        </Data>
    </ColorScale>
</CloudCompare>

```

the commented rgb(...) strings are a display convenience; my editor displays those as colorized blocks so i can look at what the colors are as i'm looking at the file itself.

Anything jump out at you as particularly off, here?   Appreciate any advice you have!

**Comment by geojames** [comment]
Graham,
It looks like you are on the right track, nothing fundamentally wrong with the XML side of things (Below is a discrete test I exported, 0-70 with only a few identified steps).

The only thing you could try is adding a dummy "zero" class so that your range is 0-155. The 'minValue' = 2 could be screwing up CloudCompare's color binning calculations. This way the math is a little easier for your class value position. simply, `[class number]/155`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<CloudCompare>
    <ColorScale version="1">
        <Properties>
            <name>LAS_CLASS_TEST</name>
            <uuid>{4876bba1-36ce-4f69-bf64-3510bc801c67}</uuid>
            <absolute>1</absolute>
            <minValue>0</minValue>
            <range>70</range>
        </Properties>
        <Data>
            <step r="255" g="255" b="255" pos="0"/>
            <step r="0" g="0" b="255" pos="0.0142857142857"/>
            <step r="35" g="0" b="220" pos="0.0285714285714"/>
            <step r="207" g="0" b="48" pos="0.0428571428571"/>
            <step r="72" g="0" b="183" pos="0.0571428571429"/>
            <step r="232" g="94" b="23" pos="0.257142857143"/>
            <step r="255" g="255" b="0" pos="1"/>
            <label val="0" text="NOT CLASS"/>
            <label val="1" text="UNCLASS"/>
            <label val="2" text="GROUND"/>
            <label val="3" text="LOW VEG"/>
            <label val="4" text="HIGH VEG"/>
            <label val="18" text="HIGH NOISE"/>
            <label val="70" text="GUY WIRE"/>
        </Data>
    </ColorScale>
</CloudCompare>
```

**Comment by gvoysey** [comment]
Interesting; i've adapted what you have slightly for a las1.2 file (so max class label is 27) and i get "scale gdi-las12-test is invalid (boundaries are not [0.0-1.0])" in the cloudcompare console window.  The color scale editor also looks completely wrong: 
![image](https://github.com/user-attachments/assets/e48b0872-ffd5-49ca-9e86-db68eb6a2be4)

![image](https://github.com/user-attachments/assets/db4752a5-81d6-4d6b-bd78-48caf3a87d8a)




```xml
<?xml version="1.0" encoding="UTF-8"?>
<CloudCompare>
    <ColorScale version="1">
        <Properties>
            <name>gdi-las12-test</name>
            <uuid>{313333e5-e6c6-4e42-b29a-4cc19db03087}</uuid>
            <absolute>1</absolute>
            <minValue>0</minValue>
            <range>27</range>
        </Properties>
        <Data>
            <step r="255" g="255" b="255" pos="0"/>          <!-- rgb(255, 255,255) -->
            <step r="85" g="0" b="0" pos="(/ 2.0 27) "/><!-- rgb(85, 0, 0) -->
            <step r="255" g="255" b="0" pos="(/ 3.0 27) "/><!-- rgb(255, 255, 0) -->
            <step r="170" g="170" b="0" pos="(/ 4.0 27) "/><!-- rgb(170,170, 0) -->
            <step r="0" g="170" b="0" pos="(/ 5.0 27) "/><!-- rgb(0, 170, 0) -->
            <step r="0" g="0" b="0" pos="(/ 10.0 27) "/><!-- rgb(0, 0, 0) -->
            <step r="255" g="85" b="0" pos="(/ 16.0 27) "/><!-- rgb(255, 85, 0) -->
            <step r="255" g="243" b="237" pos="(/ 22.0 27) "/><!-- rgb(255, 243, 237) -->
            <step r="0" g="85" b="255" pos="(/ 23.0 27) "/><!-- rgb(0, 85, 255) -->
            <step r="0" g="170" b="255" pos="(/ 24.0 27) "/><!-- rgb(0, 170, 255) -->
            <step r="0" g="255" b="255" pos="(/ 25.0 27) "/><!-- rgb(0, 255, 255) -->
            <step r="255" g="170" b="0" pos="(/ 26.0 27) "/><!-- rgb(255, 170, 0) -->
            <step r="170" g="255" b="255" pos="(/ 27 27)"/><!-- rgb(170, 255, 255)-->
            <label val="0" text="dummy"/>
            <label val="2" text="ground"/>
            <label val="3" text="low veg"/>
            <label val="4" text="medium veg"/>
            <label val="5" text="high veg"/>
            <label val="10" text="TBD"/>
            <label val="16" text="structure"/>
            <label val="22" text="pole"/>
            <label val="23" text="primary wire"/>
            <label val="24" text="prior structure wire"/>
            <label val="25" text="prior pole wire"/>
            <label val="26" text="prior pole service trap"/>
            <label val="27" text="unstrung wire"/>
        </Data>
    </ColorScale>
</CloudCompare>
```

i'm fairly stumped! i calculated the positions by just taking the classid/27 fraction, which i believe is correct.

thanks for your reply -- this is probably not the best place to get help, but the cc docs are pretty sparse here.

**Comment by geojames** [comment]
For position numbers, in the I'm pretty sure they need to be decimals, I don't think CC can interpret the variable as you have them coded `pos="(/ 27 27)"`

**Comment by gvoysey** [comment]
whoops, that was the wrong version!  

<?xml version="1.0" encoding="UTF-8"?>
<CloudCompare>
    <ColorScale version="1">
        <Properties>
            <name>gdi-las12-test</name>
            <uuid>{313333e5-e6c6-4e42-b29a-4cc19db03087}</uuid>
            <absolute>1</absolute>
            <minValue>0</minValue>
            <range>27</range>
        </Properties>
        <Data>
            <step r="255" g="255" b="255" pos="0"/>          
            <step r="85" g="0" b="0" pos="(/ 2.0 27)"/>
            <step r="255" g="255" b="0" pos="(/ 3.0 27)"/>
            <step r="170" g="170" b="0" pos="(/ 4.0 27)"/>
            <step r="0" g="170" b="0" pos="(/ 5.0 27)"/>
            <step r="0" g="0" b="0" pos="(/ 10.0 27)"/>
            <step r="255" g="85" b="0" pos="(/ 16.0 27)"/>
            <step r="255" g="243" b="237" pos="(/ 22.0 27)"/>
            <step r="0" g="85" b="255" pos="(/ 23.0 27)"/>
            <step r="0" g="170" b="255" pos="(/ 24.0 27)"/>
            <step r="0" g="255" b="255" pos="(/ 25.0 27)"/>
            <step r="255" g="170" b="0" pos="(/ 26.0 27)"/>
            <step r="170" g="255" b="255" pos="(/ 27 27)"/>
            <label val="0" text="dummy"/>
            <label val="2" text="ground"/>
            <label val="3" text="low veg"/>
            <label val="4" text="medium veg"/>
            <label val="5" text="high veg"/>
            <label val="10" text="TBD"/>
            <label val="16" text="structure"/>
            <label val="22" text="pole"/>
            <label val="23" text="primary wire"/>
            <label val="24" text="prior structure wire"/>
            <label val="25" text="prior pole wire"/>
            <label val="26" text="prior pole service trap"/>
            <label val="27" text="unstrung wire"/>
        </Data>
    </ColorScale>
</CloudCompare>

**Comment by gvoysey** [comment]
:man_facepalming:   this is what happens when you think you're being clever and you aren't -- i was using an editor plugin that i _thought_ was evaluating those expressions and replacing them with their computed value.  It wasn't, it was creating an overlay instead.  

With that remedied -- success.  thank you!
